import type { Metadata } from 'next'
import { Header } from '@/shared/components/shared/header'
import toast, { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
	title: 'My-Pizza | Главная',
	description: 'Generated by create next app',
}

export default function HomeLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode
	modal: React.ReactNode
}>) {
	return (
		<main className='min-h-screen'>
			<Header />
			{children}
			{modal}
			<Toaster />
		</main>
	)
}
